# tính từ folder public
tmpImgFolder: images/temps/
staticImgFolder: images/

app:
  port: 3100

size_widths:
  - 400
  - 600
  - 800
  - 1000
  - 1200
  - 1400

tempSize:
  width: 200

rabbitmq:
  host: 157.230.248.161
  port: 5672
  username: admin
  password: admin123

mongoURI: mongodb+srv://flowerdev:4BI41P4Hg0dzAyOZ@cluster0-gifbk.mongodb.net/flower?retryWrites=true